---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Le portefeuille digital BlueXP vous permet de gérer et de contrôler les licences BlueXP achetées avec NetApp (BYOL), les abonnements BlueXP Marketplace et NetApp Keystone.' 
---
= Découvrez le portefeuille digital BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le portefeuille digital BlueXP  vous permet de gérer et de contrôler les licences BlueXP  achetées avec NetApp (BYOL), les abonnements aux services de données BlueXP  Marketplace (y compris NetApp Cloud Volumes ONTAP) et NetApp Keystone.



== Affichage des licences et des abonnements dans le portefeuille digital

Les licences et les abonnements s'affichent automatiquement dans un portefeuille digital lorsque le compte BlueXP  utilisé pour s'abonner est également un compte sur le site de support NetApp. Si vous avez utilisé un compte BlueXP  qui n'est pas associé à votre compte sur le site de support NetApp (NSS), vous devrez ajouter et mettre à jour manuellement les licences. En outre, l'utilisation, la capacité et d'autres informations ne seront pas modifiées.

En attendant, BlueXP interroge automatiquement le service des licences NetApp pour obtenir des informations sur les licences associées à votre compte du site de support NetApp. S'il n'y a pas d'erreur, BlueXP ajoute automatiquement les licences au portefeuille digital.

Si BlueXP  ne peut pas ajouter la licence, vous devez l'ajouter manuellement au portefeuille digital. Par exemple, si votre compte utilisateur BlueXP  n'est pas associé à votre compte sur le site de support NetApp, vous devez ajouter vous-même les licences.

Après avoir acheté une licence auprès de votre représentant commercial NetApp, NetApp vous envoie un e-mail avec le numéro de série et les informations de licence supplémentaires. Vous aurez besoin de ce numéro de série pour ajouter ou mettre à jour la licence correspondante dans le portefeuille digital.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["Découvrez comment ajouter votre compte sur le site de support NetApp aux identifiants utilisateur BlueXP "^].



== Services pris en charge

Le portefeuille digital BlueXP  vous permet de gérer les licences et les abonnements pour les services suivants :

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Sauvegarde et restauration"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Reprise après incident"^] (BYOL uniquement)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protection par ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Clusters ONTAP sur site"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]

