---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Le portefeuille digital BlueXP vous permet de gérer et de contrôler les licences BlueXP achetées avec NetApp (BYOL), les abonnements BlueXP Marketplace et NetApp Keystone.' 
---
= Découvrez le portefeuille digital BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le portefeuille digital BlueXP vous permet de gérer et de contrôler les licences BlueXP achetées avec NetApp (BYOL), les abonnements BlueXP Marketplace et NetApp Keystone.



== Caractéristiques

* Gestion des licences basées sur la capacité et sur les nœuds pour Cloud Volumes ONTAP
* Ajoutez et gérez des licences pour les services de données BlueXP
* Gérez des abonnements pour PAYGO et les contrats annuels associés à votre entreprise BlueXP  et à Astra Control
* Gérez les services d'abonnement Keystone pour une utilisation avec Cloud Volumes ONTAP et les clusters ONTAP sur site et demandez des modifications de la capacité allouée
* Afficher des informations sur l'état des contrats matériels et logiciels pour les clusters ONTAP sur site




== Services pris en charge

Le portefeuille digital BlueXP vous permet de gérer les licences pour les services suivants :

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Sauvegarde et restauration"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Reprise après incident"^] (BYOL uniquement)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protection par ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Clusters ONTAP sur site"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]



TIP: Le portefeuille digital BlueXP  vous permet également de gérer les licences pour la classification BlueXP . Cependant, la classification BlueXP  est désormais disponible en tant que fonctionnalité clé au sein de BlueXP , sans frais supplémentaires. Une licence ou un abonnement n'est plus nécessaire. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["En savoir plus sur la classification BlueXP"^]
