---
settings:
  name: BlueXP digital wallet
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents relatifs aux comptes numériques BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez le portefeuille digital BlueXP
      url: "/concept-digital-wallet.html"
  - title: Utilisez le portefeuille digital BlueXP
    entries:
    - title: Utilisez le tableau de bord Aperçu
      url: "/task-homepage.html"
    - title: Gérer les licences
      entries:
      - title: Gérer les licences directes
        url: "/task-manage-data-services-licenses.html"
      - title: Gestion des licences pour Cloud Volumes ONTAP
        entries:
        - title: Licences basées sur la capacité pour Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Licences basées sur les nœuds pour Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Gérer les offres privées
      entries:
      - title: Gérer les offres privées AWS
        entries:
        - title: Gérer une offre privée AWS pour BlueXP
          url: "/task-manage-private-aws.html"
        - title: Gérer une offre privée AWS pour Data Infrastructure Insights
          url: "/task-manage-private-aws-cloud-insights.html"
      - title: Gérer les offres privées Azure
        entries:
        - title: Gérer une offre privée Azure pour BlueXP
          url: "/task-manage-private-azure.html"
        - title: Gérer une offre privée Azure pour NetApp Cloud Insights
          url: "/task-manage-private-azure-data.html"
      - title: Gérer les offres privées de Google Cloud
        entries:
        - title: Gérer une offre privée Google Cloud pour NetApp BlueXP
          url: "/task-manage-private-google-cloud.html"
    - title: Gérer les abonnements Marketplace
      url: "/task-manage-subscriptions.html"
    - title: Gérez les abonnements Keystone
      url: "/task-manage-keystone.html"
    - title: Gérez les licences pour ONTAP sur site
      url: "/task-manage-on-prem-clusters.html"
    - title: Connaissances et support
      entries:
      - title: S'inscrire pour obtenir de l'aide
        url: "/task-support-registration.html"
      - title: Obtenez de l'aide
        url: "/task-get-help.html"
    - title: Mentions légales
      url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
