= Offres privées Google Cloud
:allow-uri-read: 




=== Offres privées Google Cloud

Le portefeuille digital BlueXP identifie désormais les abonnements Google Cloud Marketplace associés à une offre privée et affiche la date de fin et la durée de l'abonnement. Cette amélioration vous permet de vérifier que vous avez bien accepté l'offre privée et de valider ses conditions.



=== Répartition de l'utilisation de la charge

Vous pouvez désormais connaître les frais facturés lorsque vous souscrivez à des licences basées sur la capacité. Les types de rapports d'utilisation suivants sont disponibles au téléchargement depuis le portefeuille digital BlueXP. Les rapports d'utilisation fournissent des détails sur la capacité de vos abonnements et vous indiquent comment vous facturez les ressources de vos abonnements Cloud Volumes ONTAP. Les rapports téléchargeables peuvent être facilement partagés avec d'autres personnes.

* Utilisation du package Cloud Volumes ONTAP
* Utilisation générale
* Utilisation des VM de stockage
* Utilisation des volumes


Pour plus d'informations sur les rapports d'utilisation, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Télécharger les rapports d'utilisation"].
